# Generated by Django 3.0.5 on 2020-04-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersauth', '0006_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='group_name',
        ),
    ]
