# Generated by Django 3.0.5 on 2020-04-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersauth', '0007_remove_usergroup_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='group_name',
            field=models.CharField(default='enter group name', max_length=100, unique=True, verbose_name='用户组'),
        ),
    ]
